### ISSUE TITLE
DNS changes.

### ISSUE THREAD

**Issue by stopfstedt** [ucsf-ckm/ucsf-japanese-woodblock-print-collection#1]
point asian.library.ucsf.edu away from the Drupal 6 version of this site to GH pages.

@Trott - here's an opportunity to move away from this awful domain name. suggestions?

**Comment by Trott** [comment]
japanesewoodblockprints.library.ucsf.edu

It's a lot to type, but a lot less cringe-incucing.

**Comment by stopfstedt** [comment]
DNS requested. For reference, see RITM0074494 in SN.
