### ISSUE TITLE
remove flash-powered carousel from landing page.

### ISSUE THREAD

**Issue by stopfstedt** [ucsf-ckm/ucsf-japanese-woodblock-print-collection#10]
![Selection_075](https://user-images.githubusercontent.com/1410427/70578010-62b49180-1b61-11ea-838e-b4ba97880156.png)

**Comment by Trott** [comment]
Perhaps replacing it with a static image will be a good temporary (or even permanent) solution? I suspect Charlie or Polina would be willing to suggest a hi-res image. @mizejewski

**Comment by Trott** [comment]
Another temporary (or permanent) options would be to just remove it entirely.
