### ISSUE TITLE
resubmit brand XML to the CDL.

### ISSUE THREAD

**Issue by stopfstedt** [ucsf-ckm/ucsf-japanese-woodblock-print-collection#14]
refs #9 
refs #2 

instructions here: https://wiki.library.ucsf.edu/display/Library/Docs+for+Japanese+Prints+Project

**Comment by tingletech** [comment]
https://bitbucket.org/btingle/dsc-xtf/commits/cd8aad192d0c63f8762100f33459599a6e16ef7e

**Comment by stopfstedt** [comment]
resolved.
