### ISSUE TITLE
resubmit woodblock.xml to the CDL.

### ISSUE THREAD

**Issue by stopfstedt** [ucsf-ckm/ucsf-japanese-woodblock-print-collection#2]
somewhere in the library wiki, there is further info about who our contact is on the other side/how this process works. i believe.

this needs to be timed with the DNS switch-over outlined in #1.

**Comment by stopfstedt** [comment]
depending on whether we continue hosting under the same domain name or not, changes may be required in `woodblock.xml`.

**Comment by stopfstedt** [comment]
`woodblock.xml` has been updated to point at japanesewoodblockprints.library.ucsf.edu. 

also, both versions of the site are online right now, with synchronized content. no switch-over needs to be coordinated.

**Comment by stopfstedt** [comment]
requested brand file update from CDL|OAC-operations via email.

**Comment by tingletech** [comment]
https://bitbucket.org/btingle/dsc-xtf/commits/0371fa60467c56b9f5a34016a7d656b4342f8440

pushed to -prod

FYI, there is an on-going issue with extra logging in google analytics.  You stats are double the actual usage.

**Comment by tingletech** [comment]
https://bitbucket.org/btingle/dsc-xtf/pull-requests/1/added-cdls-custom-var-to-ga-rollup-account/diff#chg-brand/woodblock.xml Ticket #385 in freshdesk
